IF OBJECT_ID('Form') IS NULL
BEGIN
CREATE TABLE Form(
Id INT NOT NULL PRIMARY KEY IDENTITY,
Name VARCHAR(500) NOT NULL,
Lock BIT NOT NULL,
Active BIT NOT NULL)
END
GO


IF NOT EXISTS (SELECT * FROM PermissionRecord WHERE SystemName = 'ManageForms')
BEGIN
INSERT INTO PermissionRecord (Name,SystemName,Category) VALUES
('Admin area. Manage Forms', 'ManageForms', 'Configuration')
END
GO

IF OBJECT_ID('FormField') IS NULL
BEGIN
CREATE TABLE FormField(
Id INT NOT NULL PRIMARY KEY IDENTITY,
Name VARCHAR(500) NOT NULL,
DisplayOrder INT NOT NULL,
ControlTypeId INT NOT NULL,
Required BIT NOT NULL,
FormId INT NOT NULL FOREIGN KEY REFERENCES Form(Id))
END
GO

IF OBJECT_ID('FormFieldOption') IS NULL
BEGIN
CREATE TABLE FormField(
Id INT NOT NULL PRIMARY KEY IDENTITY,
Name VARCHAR(500) NOT NULL,
DisplayOrder INT NOT NULL,
FormFieldId INT NOT NULL FOREIGN KEY REFERENCES FormField(Id))
END
GO

