IF COL_LENGTH('StudentExtension', 'DateOfAdmission') IS NULL
BEGIN
ALTER TABLE StudentExtension ADD DateOfAdmission DATETIME NULL
END
GO

IF OBJECT_ID('StudentLeave') IS NULL
BEGIN
CREATE TABLE StudentLeave(
Id INT NOT NULL PRIMARY KEY IDENTITY,
CustomerId INT NOT NULL FOREIGN KEY REFERENCES Customer(Id) ON DELETE CASCADE,
StartDate DATETIME NOT NULL,
EndDate DATETIME NOT NULL)
END
GO

