name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  DOTNET_VERSION: '8.0.x'                 # set this to the .NET Core version to use
  PUBLISHED_PATH: ./publish_output

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.PUBLISHED_PATH}}
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.PUBLISHED_PATH}}
          
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{env.PUBLISHED_PATH}}
      
      - name: Check publish output exists
        run: ls -la ${{env.PUBLISHED_PATH}}

      - name: FTP Deploy using lftp
        uses: pontago/lftp-deploy-action@v1.0.1
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local_dir: .${{env.PUBLISHED_PATH}}
          remote_dir: /httpdocs/  # or any directory where you deploy your app
          options: "--verbose --continue --retry 3 --parallel=4"

      
      # - name: FTP Transfer
      #   # You may pin to the exact commit or the version.
      #   uses: joutvhu/ftp-transfer@v1.0.0
      #   with:
      #     # Sever Hostname or IP
      #     host: ${{ secrets.FTP_HOST }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     commands: |
      #       open ${{ secrets.FTP_HOST }}
      #       mirror -R ${{env.PUBLISHED_PATH}} /
