name: FTP Deploy for NopCommerce

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Adjust this based on your NopCommerce version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet publish ./src/Presentation/Nop.Web/Nop.Web.csproj -c Release -o ./published

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: 64.27.52.66
        username: dev-ftp-account
        password: 5ggYNtVRCa%3*dS6
        local-dir: ./published/
        server-dir: /
